### ISSUE TITLE
Wrong path for TA_DEV_KIT_DIR in rpi4-ws

### ISSUE THREAD

**Issue by YPaulus-CYSEC** [crosscon/CROSSCON-Hypervisor-and-TEE-Isolation-Demos#4]
The TA_DEV_KIT_DIR variable declared in steps 4, 5 and 6 is not declared correctly. It should be `optee_os/optee-rpi4/export-ta_arm64` to match the nomenclature used in the guide.

**Comment by DavidMCerdeira** [comment]
Greetings,
I fixed this in the latest commit.
I'm closing the issue
